config/routes.rb
Rails.application.routes.draw do

  get 'vetrina' => 'entities#vetrina'

  resources :grades
  resources :homeworks
  resources :assignments
  resources :instances
  resources :properties
  resources :entities
  resources :photos
  resources :photoalbums do
    member do
      get 'copertina'
      get 'pubblica'
    end
  end
  resources :tags

  resources :attachments do
    member do
      get 'download/:filename' => 'attachments#download'
      get 'pubblica'
    end
  end

  devise_for :users
  scope "/admin" do
    resources :users
  end

  mount Ckeditor::Engine => '/ckeditor'

  get 'login', to: redirect('/users/sign_in')
  get 'logout', to: redirect('/users/sign_out')

  resources :columns do
    member do
      post 'editor_update'
      post 'estendi_riga'
      post 'riduci_riga'
      post 'inserisci_riga_prima'
      post 'inserisci_riga_dopo'
      post 'elimina_riga'
      post 'inserisci_colonna_prima'
      post 'inserisci_colonna_dopo'
      post 'allarga_colonna'
      post 'stringi_colonna'
      post 'elimina_colonna'
      post 'rendi_statica'
      post 'elimina_contenuto_dinamico'
      post 'aggiungi_ruolo_titolo'
      post 'aggiungi_ruolo_abstract'
      post 'aggiungi_ruolo_testo'
      post 'cancella_ruolo'
      post 'contenuti_dinamici_pagina'
      post 'contenuti_dinamici_sezione'
      post 'contenuti_dinamici_sito'
      post 'sposta_riga_prima'
      post 'sposta_riga_dopo'
      post 'duplica_riga'
      post 'sposta_colonna_prima'
      post 'sposta_colonna_dopo'
      post 'equalizza_colonne'
      post 'autocrop_on'
      post 'autocrop_off'
      post 'mostra_sempre'
      post 'mostra_small_only'
      post 'mostra_big_only'
      post 'padding_00'
      post 'padding_01'
      post 'padding_02'
      post 'padding_03'
      post 'padding_04'
      post 'padding_05'
      post 'padding_10'
      post 'padding_15'
      post 'padding_20'
      post 'padding_25'
      post 'padding_30'
      get 'dialog_sfondo'
      get 'dialog_immagine'
      get 'modifica_immagine'
    end
  end

  resources :rows

  resources :sections

  resources :pages do
    member do
      get 'route'
      get 'row0'
      get 'pubblica'
      get 'duplica'
      get 'nascondi'
      post 'nuovo_contenuto_dinamico'
    end
  end

  resources :column_images do
    member do
      post 'elimina'
      post 'sposta_sx'
      post 'sposta_dx'
    end
  end

  get 'profile-updated' => 'users#profile_updated'
  get 'edit-profile' => 'users#edit_profile'
  get 'screen/:n' => 'pages#screen'
  get 'search' => 'pages#search'
  get 'tag-cloud-3d' => 'tags#cloud3d'
  get 'tag-cloud' => 'tags#cloud'
  get ':slug' => 'pages#route'
  get 'articoli/articolo.php' => 'pages#search'

  root 'pages#route', as: 'home'

end

app/models/instance.rb
class Instance < ActiveRecord::Base
  belongs_to :entity
  belongs_to :section
  belongs_to :user

  has_many :data, dependent: :destroy

  def label
    name_properties = Property.where("entity_id = ? AND indice = ? AND nome NOT LIKE 'limite'", self.entity.id, true).order(:ordine)

    if name_properties.count >= 1
      label = ''
      name_properties.each do |name_property|
        if name_property.tipo == 'select'
          datum = Datum.find_by instance_id: self.id, property_id: name_property.id
          instance = Instance.where("id = ?", datum.valore).first
          label+= "#{instance.label} " if instance
        elsif name_property.tipo == 'utente' && self.user
          label+= self.user.profilo.label
          label+= ' - ' + self.user.appartenenza if !self.user.appartenenza.empty?
        else
          datum = Datum.find_by instance_id: self.id, property_id: name_property.id
          label+= "#{datum.valore} " if datum
        end
      end
    end

    if label
      label.strip
    else
      "#{self.entity.titolo} #{self.id}"
    end
  end

  # label in formato array
  def alabel
    label = []

    name_properties = Property.where("entity_id = ? AND indice = ?", self.entity.id, true).order(:ordine)

    if name_properties.count >= 1
      name_properties.each do |name_property|
        if name_property.tipo == 'select'
          datum = Datum.find_by instance_id: self.id, property_id: name_property.id
          instance = Instance.where("id = ?", datum.valore).first
          if instance
            label << "#{instance.label}"
          else
            label << ''
          end
        elsif name_property.tipo == 'utente' && self.user
          buffer = self.user.profilo.label
          buffer+= ' - ' + self.user.appartenenza if !self.user.appartenenza.empty?
          label << buffer
        elsif name_property.tipo == 'check'
          datum = Datum.find_by instance_id: self.id, property_id: name_property.id
          if datum
            label << (datum.valore == '1' ? '<i class="fi-check"></i>'.html_safe : '')
          else
            label << ''
          end
        else
          datum = Datum.find_by instance_id: self.id, property_id: name_property.id
          if datum
            label << "#{datum.valore}"
          else
            label << ''
          end
        end
      end
    else
      label << "#{self.entity.titolo} #{self.id}"
    end

    label
  end

  self.per_page = 20
end

app/controllers/instances_controller.rb
class InstancesController < ApplicationController
  before_action :set_instance, only: [:show, :edit, :update, :destroy]

  # GET /instances
  # GET /instances.json
  def index
    if !params[:type].nil?
      @entity = Entity.find_by slug: params[:type]

      authorize @entity, :show?

      # se richiesto prende pagina e ordinamento dalla sessione
      if params[:pfs]
        params[:page] = session[:pagina_corrente]
        params[:sort_by] = session[:sort_by]
        params[:sort_dir] = session[:sort_dir]
      end
      params.delete :pfs

      @instances = @entity.elenco(params[:sort_by], params[:sort_dir])

      if !current_user.admin? || @entity.slug == 'persona'
        @instances = @instances.where user_id: current_user.id
      end

      @numero = @instances.count
      @paganti = @numero
      @paganti-=1 if @entity.capogruppo_gratuito > 0 && @numero>= @entity.capogruppo_gratuito

      respond_to do |format|
        format.html {
          @instances = @instances.page(params[:page])
          session[:pagina_corrente] = params[:page]
          session[:sort_by] = params[:sort_by]
          session[:sort_dir] = params[:sort_dir]
        }
        format.xlsx { # niente paginazione
          response.headers['Content-Disposition'] = 'attachment; filename="' + @entity.plurale + '.xlsx"'
        }
      end

    else
      redirect_to '/'
    end
  end

  # GET /instances/1
  # GET /instances/1.json
  def show
    @entity = @instance.entity
  end

  # GET /instances/new
  def new
    @instance = Instance.new
    @instance.user = current_user
    @page = trova_home
    @avvisi_limiti = []

    if !params[:type].nil?
      @entity = Entity.find_by! slug: params[:type]
      @instance.entity_id = @entity ? @entity.id : 0

      authorize @entity, :edit_instances?

      # verifica se ci sono limiti per appartenenza
      if @instance.entity.applica_limiti_appartenenza
        entity_appartenenza = Entity.find_by! slug: 'appartenenza'
        appartenenza = entity_appartenenza.instances.where(id: current_user.appartenenza_id).first
        # nota: non si può semplificare in Instance.find(instance.user.appartenenza_id) perché nel caso non esistesse solleverebbe un'eccezione

        if appartenenza
          limit_property = Property.where("entity_id = ? AND nome like 'limite'", entity_appartenenza.id).first

          if limit_property
            datum = Datum.find_by instance_id: current_user.appartenenza_id, property_id: limit_property.id
            max = datum ? datum.valore.to_i : 0
            conteggio = Instance.where(entity_id: @instance.entity.id, appartenenza_id: current_user.appartenenza_id).count

            if conteggio >= max
              if max > 0
                @avvisi_limiti << "Siamo spiacenti, non ci sono più posti disponibili per #{ appartenenza.label }: #{ conteggio } posti occupati."
              else
                @avvisi_limiti << "#{ appartenenza.label } partecipa per la prima volta. Contatta eventijesolo@donboscoland.it per abilitare l'iscrizione."
              end
            else
              @avvisi_limiti << "Disponibili ancora #{ max - conteggio } su #{ max } posti per #{ appartenenza.label }"
            end
          end
        end
      end
    else
      # todo: errore, tipo di oggetto non specificato
      @instance.entity_id = 0
    end
  end

  # GET /instances/1/edit
  def edit
    @entity = @instance.entity
    @page = trova_home
  end

  # POST /instances
  # POST /instances.json
  def create
    # è possibile creare diverse copie dell'istanza
    numcopie = params[:numcopie].to_i
    numcopie = 1 if !numcopie.between?(1,200)

    copie_salvate = 0

    for i in 1..numcopie

      @instance = Instance.new(instance_params)
      @instance.section||= trova_sezione_principale
      @instance.user = current_user
      @instance.appartenenza_id = current_user.appartenenza_id

      authorize @instance

      @entity = @instance.entity

      @errori_limiti = []
      @limiti_superati = !(nei_limiti? @instance)

      if !@limiti_superati && (valid_properties? @entity)
        if @instance.save
          copie_salvate+=1

          # scrittura dei valori delle singole proprietà
          properties = @entity.properties
          properties = properties.where(riservata: false) if !current_user.admin?
          properties.each do |property|
            if property.tipo!='utente'
              datum = Datum.new
              datum.instance = @instance
              datum.property = property
              datum.valore = params[:dato][property.id.to_s]
              datum.valore = datum.valore.strip if datum.valore
              datum.valore = datum.valore.mb_chars.upcase.to_s if property.maiuscolo
              datum.save
            end
          end

          @instance.update_attribute :proxy, @instance.label
        else
          break
        end
      else
        break
      end
    end

    if copie_salvate == numcopie # ha completato il ciclo
      landing_page = !@entity.landing_page.empty? ? @entity.landing_page : instances_url(type: @entity.slug, pfs: 1)
      redirect_to landing_page
    else
      @errori_limiti << "Salvate #{ copie_salvate } copie su #{ numcopie }"
      render :new
    end
  end

  # PATCH/PUT /instances/1
  # PATCH/PUT /instances/1.json
  def update
    @entity = @instance.entity

    @errori_limiti = []
    @limiti_superati = !(nei_limiti? @instance, true)

    if !@limiti_superati && (valid_properties? @entity)
      respond_to do |format|
        if @instance.update(instance_params)

          # scrittura dei valori delle singole proprietà
          properties = @entity.properties
          properties = properties.where(riservata: false) if !current_user.admin?
          properties.each do |property|
            if property.tipo!='utente'
              datum = Datum.find_by instance_id: @instance.id, property_id: property.id
              if !datum
                datum = Datum.new
                datum.instance = @instance
                datum.property = property
              end
              datum.valore = params[:dato][property.id.to_s]
              datum.valore = datum.valore.strip if datum.valore
              datum.valore = datum.valore.mb_chars.upcase.to_s if property.maiuscolo
              datum.save
            end
          end

          @instance.update_attribute :proxy, @instance.label

          landing_page = !@entity.landing_page.empty? ? @entity.landing_page : instances_url(type: @entity.slug, pfs: 1)

          format.html { redirect_to landing_page }
          format.json { render :show, status: :ok, location: @instance }
        else
          format.html { render :edit }
          format.json { render json: @instance.errors, status: :unprocessable_entity }
        end
      end
    else
      render :edit
    end
  end

  # DELETE /instances/1
  # DELETE /instances/1.json
  def destroy
    type = @instance.entity.slug

    @instance.destroy
    respond_to do |format|
      format.html { redirect_to instances_url(type: type, pfs: 1), notice: 'Instance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instance
      @instance = Instance.find(params[:id])

      authorize @instance
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instance_params
      params.require(:instance).permit(:entity_id, :section_id, :tags, :type, :dato, :numcopie )
    end

    def valid_properties?(entity)
      parametri = {}
      validatori = {}

      properties = entity.properties
      properties = properties.where(riservata: false) if !current_user.admin?
      properties.each do |property|
        if property.tipo!='utente'
          # da rimuovere: 'p' + property.id.to_s
          parametri['p' + property.id.to_s] = params[:dato][property.id.to_s]

          validatori['p' + property.id.to_s] = {:presence => true} if property.obbligatorio
        end
      end

      @validator = DataValidator.make(
          parametri,
          validatori
      )

      @validator.valid?
    end

  def nei_limiti?(instance, is_update = false)
    nei_limiti = true

    # verifica che non sia superato il limite per questa appartenenza (bypassata nel caso dell'update)
    if instance.entity.applica_limiti_appartenenza
      if !is_update

        entity_appartenenza = Entity.find_by! slug: 'appartenenza'
        appartenenza = entity_appartenenza.instances.where(id: instance.user.appartenenza_id).first
        # nota: non si può semplificare in Instance.find(instance.user.appartenenza_id) perché nel caso non esistesse solleverebbe un'eccezione

        if appartenenza
          limit_property = Property.where("entity_id = ? AND nome like 'limite'", entity_appartenenza.id).first

          if limit_property
            datum = Datum.find_by instance_id: instance.user.appartenenza_id, property_id: limit_property.id

            max = datum ? datum.valore.to_i : 0

            conteggio = Instance.where(entity_id: instance.entity.id, appartenenza_id: instance.user.appartenenza_id).count

            if conteggio >= max
              nei_limiti = false
              if max > 0
                @errori_limiti << "Siamo spiacenti, non ci sono più posti disponibili per #{ appartenenza.label }"
              else
                @errori_limiti << "#{ appartenenza.label } partecipa per la prima volta. Contatta iscrizioni@donboscoland.it per abilitare l'iscrizione."
              end
            end
          end
        end
      end
    end

    if instance.entity.applica_limiti
      # per ogni property di tipo select
      select_properties = instance.entity.properties.where(tipo: 'select')
      select_properties.each do |property|
        # trovo l'entity collegata
        parametri = property.condizioni.split(',')
        tabella = parametri[0]

app/helpers/instances_helper.rb
module InstancesHelper
end

app/views/instances/edit.html.erb
<%= render partial: "pages/cookielaw" %>
<%= render partial: "pages/header" %>

<% if @entity.immagine.exists? %>
    <div style='background: #ffffff;'>
      <div class="collapse row">
        <div class="large-12 columns" style="position: relative; padding: 0em;">
          <div class='cropped-30'><img src='<%= @entity.immagine.url(:large) %>' class='cropped-image'></div>
        </div>
      </div>
    </div>
<% end %>

<div class="row">
  <p>&nbsp;</p>

<h2>Modifica <%= @entity.titolo %>
  <%= link_to 'Elenco', "/instances?type=#{ @entity.slug }", class: 'secondary button float-right' %>
</h2>

<%= render 'form' %>

<p>&nbsp;</p>
</div>

<%= render partial: "pages/footer" %>

app/views/instances/index.html.erb
<%= render partial: "pages/cookielaw" %>
<%= render partial: "pages/header" %>

<% if @entity.immagine.exists? %>
    <div style='background: #ffffff;'>
      <div class="collapse row">
        <div class="large-12 columns" style="position: relative; padding: 0em;">
          <div class='cropped-30'><img src='<%= @entity.immagine.url(:large) %>' class='cropped-image'></div>
        </div>
      </div>
    </div>
<% end %>

<%
  case @entity.tipo
    when 'iscrizione'
      bottone_new = 'Iscrivi'
    when 'ordine'
      bottone_new = 'Ordina'
    when 'oggetto'
      bottone_new = 'Nuovo'
    else
      bottone_new = 'Nuovo'
  end
%>

<div class="row">
  <p>&nbsp;</p>

<h2><%= @entity.plurale %>
<%= link_to bottone_new, new_instance_path + "?type=#{ @entity.slug }", class: 'large warning button float-right' if @entity %>
<% if @entity %><%= link_to 'Xlsx', instances_path(format: :xlsx) + "?type=#{ @entity.slug }", class: 'large primary button float-right' %><% end %>
</h2>
<span class="secondary label"><%= @numero %> elementi</span>

<table>
  <thead>
    <tr>
      <% if current_user.admin? %>
        <th>id
          <a href="/instances?type=<%= @entity.slug %>&sort_by=id&sort_dir=desc"><i class="fi-arrow-down float-right"></i></a>
          <a href="/instances?type=<%= @entity.slug %>&sort_by=id&sort_dir=asc"><i class="fi-arrow-up float-right"></i></a>
        </th>
      <% end %>
      <% @entity.plabel.each do |label| %>
        <th><%= label.nome %>
          <a href="/instances?type=<%= @entity.slug %>&sort_by=<%= label.id %>&sort_dir=desc"><i class="fi-arrow-down float-right"></i></a>
          <a href="/instances?type=<%= @entity.slug %>&sort_by=<%= label.id %>&sort_dir=asc"><i class="fi-arrow-up float-right"></i></a>
        </th>
      <% end %>
      <% if current_user.admin? %>
          <th>Creato da
            <a href="/instances?type=<%= @entity.slug %>&sort_by=utente&sort_dir=desc"><i class="fi-arrow-down float-right"></i></a>
            <a href="/instances?type=<%= @entity.slug %>&sort_by=utente&sort_dir=asc"><i class="fi-arrow-up float-right"></i></a>
          </th>
          <th>Appartenenza
            <a href="/instances?type=<%= @entity.slug %>&sort_by=appartenenza&sort_dir=desc"><i class="fi-arrow-down float-right"></i></a>
            <a href="/instances?type=<%= @entity.slug %>&sort_by=appartenenza&sort_dir=asc"><i class="fi-arrow-up float-right"></i></a>
          </th>
          <th>Ultima modifica
            <a href="/instances?type=<%= @entity.slug %>&sort_by=modifica&sort_dir=desc"><i class="fi-arrow-down float-right"></i></a>
            <a href="/instances?type=<%= @entity.slug %>&sort_by=modifica&sort_dir=asc"><i class="fi-arrow-up float-right"></i></a>
          </th>
      <% end %>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @instances.each do |instance| %>
      <%
        logger.debug instance.data.inspect
      %>
      <tr>
        <% if current_user.admin? %>
          <td class="testo_piccolo text-center"><%= instance.id %></td>
        <% end %>
        <% instance.alabel.each do |label| %>
          <% if current_user.admin? || instance.entity.stato == 1 %>
            <td><%= link_to label, edit_instance_path(instance) %></td>
          <% else %>
            <td><%= link_to label, instance_path(instance) %></td>
          <% end %>
        <% end %>
        <% if current_user.admin? %>
            <td class="testo_piccolo"><%= instance.user.email if instance.user %></td>
            <td class="testo_piccolo"><%= instance.user.appartenenza if instance.user %></td>
            <td class="testo_piccolo"><%= instance.updated_at.to_s(:data_ora) %></td>
        <% end %>
        <% if current_user.admin? || instance.entity.stato == 1 %>
          <td><%= link_to 'Elimina', instance, method: :delete, data: { confirm: 'Are you sure?' }, class: 'small alert button' %></td>
        <% else %>
          <td>&nbsp;</td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

  <p>&nbsp;</p>
</div>

<div class="text-center">
  <%= will_paginate @instances, renderer: FoundationPagination::Rails %>
</div>

<div class="row small-12 columns">
  <p>&nbsp;</p>
  <% if @entity.prezzo > 0 %>
    <div class="warning callout" data-closable="scale-out-up">
      <h2>Informazioni per il pagamento</h2>
      <p>Totale da versare: &euro; <%= number_to_currency @paganti*@entity.prezzo, locale: :it, unit: '' %></p>
      <p><%= simple_format @entity.testo_pagamento %></p>
      <% if @entity.caparra > 0 %><p>Si ricorda che la caparra non rimborsabile ammonta a &euro; <%= number_to_currency @paganti*@entity.caparra, locale: :it, unit: '' %> </p><% end %>

      <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

<%= render partial: "pages/footer" %>

app/views/instances/new.html.erb
<%= render partial: "pages/cookielaw" %>
<%= render partial: "pages/header" %>

<% if @entity.immagine.exists? %>
<div style='background: #ffffff;'>
  <div class="collapse row">
    <div class="large-12 columns" style="position: relative; padding: 0em;">
      <div class='cropped-30'><img src='<%= @entity.immagine.url(:large) %>' class='cropped-image'></div>
    </div>
  </div>
</div>
<% end %>

<div class="row">
  <p>&nbsp;</p>

<h2><%= @entity.titolo %>
  <%= link_to 'Elenco', "/instances?type=#{ @entity.slug }", class: 'secondary button float-right' %>
</h2>

<%= ("<div style='font-size: 0.7rem;'>" + simple_format("#{ @entity.descrizione_lunga}") + "</div>").html_safe if @entity.descrizione_lunga %>

<%= render 'form' %>

<p>&nbsp;</p>
</div>

<%= render partial: "pages/footer" %>

app/views/instances/show.html.erb
<%= render partial: "pages/cookielaw" %>
<%= render partial: "pages/header" %>

<% if @entity.immagine.exists? %>
    <div style='background: #ffffff;'>
      <div class="collapse row">
        <div class="large-12 columns" style="position: relative; padding: 0em;">
          <div class='cropped-30'><img src='<%= @entity.immagine.url(:large) %>' class='cropped-image'></div>
        </div>
      </div>
    </div>
<% end %>

<div class="row">

<h1><%= @entity.titolo %></h1>

<% @entity.properties.where("riservata = ?", false).each do |property| %>
  <br><% dato = Datum.find_by instance_id: @instance.id, property_id: property.id %>
      <%= property.nome %>:

      <b>
      <%=
      if property.tipo == 'select' && dato
        instance = Instance.where("id = ?", dato.valore).first
        instance.label if instance
      elsif property.tipo == 'utente' && @instance.user
        @instance.user.profilo.label
      else
        dato.valore if dato
      end
      %>
      </b>
<% end %>

<p>&nbsp;</p>
</div>

<%= render partial: "pages/footer" %>