config/routes.rb
Rails.application.routes.draw do

  get 'vetrina' => 'entities#vetrina'

  resources :grades
  resources :homeworks
  resources :assignments
  resources :instances
  resources :properties
  resources :entities
  resources :photos
  resources :photoalbums do
    member do
      get 'copertina'
      get 'pubblica'
    end
  end
  resources :tags

  resources :attachments do
    member do
      get 'download/:filename' => 'attachments#download'
      get 'pubblica'
    end
  end

  devise_for :users
  scope "/admin" do
    resources :users
  end

  mount Ckeditor::Engine => '/ckeditor'

  get 'login', to: redirect('/users/sign_in')
  get 'logout', to: redirect('/users/sign_out')

  resources :columns do
    member do
      post 'editor_update'
      post 'estendi_riga'
      post 'riduci_riga'
      post 'inserisci_riga_prima'
      post 'inserisci_riga_dopo'
      post 'elimina_riga'
      post 'inserisci_colonna_prima'
      post 'inserisci_colonna_dopo'
      post 'allarga_colonna'
      post 'stringi_colonna'
      post 'elimina_colonna'
      post 'rendi_statica'
      post 'elimina_contenuto_dinamico'
      post 'aggiungi_ruolo_titolo'
      post 'aggiungi_ruolo_abstract'
      post 'aggiungi_ruolo_testo'
      post 'cancella_ruolo'
      post 'contenuti_dinamici_pagina'
      post 'contenuti_dinamici_sezione'
      post 'contenuti_dinamici_sito'
      post 'sposta_riga_prima'
      post 'sposta_riga_dopo'
      post 'duplica_riga'
      post 'sposta_colonna_prima'
      post 'sposta_colonna_dopo'
      post 'equalizza_colonne'
      post 'autocrop_on'
      post 'autocrop_off'
      post 'mostra_sempre'
      post 'mostra_small_only'
      post 'mostra_big_only'
      post 'padding_00'
      post 'padding_01'
      post 'padding_02'
      post 'padding_03'
      post 'padding_04'
      post 'padding_05'
      post 'padding_10'
      post 'padding_15'
      post 'padding_20'
      post 'padding_25'
      post 'padding_30'
      get 'dialog_sfondo'
      get 'dialog_immagine'
      get 'modifica_immagine'
    end
  end

  resources :rows

  resources :sections

  resources :pages do
    member do
      get 'route'
      get 'row0'
      get 'pubblica'
      get 'duplica'
      get 'nascondi'
      post 'nuovo_contenuto_dinamico'
    end
  end

  resources :column_images do
    member do
      post 'elimina'
      post 'sposta_sx'
      post 'sposta_dx'
    end
  end

  get 'profile-updated' => 'users#profile_updated'
  get 'edit-profile' => 'users#edit_profile'
  get 'screen/:n' => 'pages#screen'
  get 'search' => 'pages#search'
  get 'tag-cloud-3d' => 'tags#cloud3d'
  get 'tag-cloud' => 'tags#cloud'
  get ':slug' => 'pages#route'
  get 'articoli/articolo.php' => 'pages#search'

  root 'pages#route', as: 'home'

end

app/models/entity.rb
class Entity < ActiveRecord::Base
  extend FriendlyId

  belongs_to :user

  has_many :properties, dependent: :destroy
  has_many :instances, dependent: :destroy

  friendly_id :slug_candidates, :use => :slugged

  has_attached_file :immagine,
                    :hash_secret => "hj42ZZ5!76",
                    :url  => "/img/entity/:hash.:extension",
                    :path => ":rails_root/public/img/entity/:hash.:extension",
                    :styles => {
                        :thumb => '400x250#',
                        :medium => '1024>',
                        :large => '1200>'
                    },
                    :convert_options => {
                        :thumb => "-quality 75 -strip",
                        :medium => "-quality 75 -strip",
                        :large => "-quality 75 -strip"
                    },
                    :default_url => "/img/missing.png"

  validates_attachment_size :immagine, :less_than => 3.megabytes
  validates_attachment_content_type :immagine, :content_type => /\Aimage/

  has_attached_file :icona_on,
                    :hash_secret => "hj42ZZ5!76",
                    :url  => "/img/entity/on/:hash.:extension",
                    :path => ":rails_root/public/img/entity/on/:hash.:extension",
                    :styles => {
                        :thumb => '256x256#',
                    },
                    :convert_options => {
                        :thumb => "-quality 75 -strip",
                    },
                    :default_url => "/img/entity/oggetto.png"

  validates_attachment_size :icona_on, :less_than => 3.megabytes
  validates_attachment_content_type :icona_on, :content_type => /\Aimage/

  has_attached_file :icona_off,
                    :hash_secret => "hj42ZZ5!76",
                    :url  => "/img/entity/off/:hash.:extension",
                    :path => ":rails_root/public/img/entity/off/:hash.:extension",
                    :styles => {
                        :thumb => '256x256#',
                    },
                    :convert_options => {
                        :thumb => "-quality 75 -strip",
                    },
                    :default_url => "/img/entity/oggetto_disabled.png"

  validates_attachment_size :icona_off, :less_than => 3.megabytes
  validates_attachment_content_type :icona_off, :content_type => /\Aimage/

  def slug_candidates
    [ :titolo, :titolo_e_sequenza ]
  end

  def titolo_e_sequenza
    slug = normalize_friendly_id(titolo)
    sequence = self.class.where("slug like '#{slug}-%'").count + 2
    "#{slug}-#{sequence}"
  end

  def label
    name_properties = Property.where("entity_id = ? AND indice = ? AND nome NOT LIKE 'limite'", self.id, true).order(:ordine)

    if name_properties.count >= 1
      label = ''
      name_properties.each do |name_property|
        label+= "#{name_property.nome} "
      end
    end

    if label
      label.strip
    else
      "#{self.titolo} n."
    end
  end

  # label in formato array
  def alabel
    label = []

    name_properties = Property.where("entity_id = ? AND indice = ?", self.id, true).order(:ordine)

    if name_properties.count >= 1
      name_properties.each do |name_property|
        label << "#{name_property.nome} "
      end
    else
      label << "#{self.titolo} n."
    end

    label
  end

  # label in formato property
  def plabel
    Property.where("entity_id = ? AND indice = ?", self.id, true).order(:ordine)
  end

  def elenco(sort_by = '', sort_dir = 'asc')
    need_index_property = true
    sort_dir = 'ASC' if !sort_dir.in?(['asc','desc'])

    if sort_by
      if sort_by=='id'
        ordinamento = "id #{sort_dir}"
        need_index_property = false
      elsif sort_by=='modifica'
        ordinamento = "updated_at #{sort_dir}"
        need_index_property = false
      elsif sort_by=='appartenenza'
        ordinamento = "appartenenza_id #{sort_dir}"
        need_index_property = false
      elsif sort_by=='utente'
        ordinamento = "user_id #{sort_dir}"
        need_index_property = false
      else # abbiamo bisogno di una index property
        index_property = Property.where("entity_id = ? AND id = ? AND tipo NOT IN ('utente')", self.id, sort_by.to_i).first
        if index_property
          if index_property.tipo=='intero'
            ordinamento = "data.valore + 0 #{ sort_dir }"
          elsif index_property.tipo=='select'
            ordinamento = "i2.proxy #{ sort_dir }"
          end
        end
      end
    end

    # se non è stata specificata una index property prendo la prima disponibile
    if !index_property && need_index_property
      index_property = Property.where("entity_id = ? AND indice = ? AND tipo NOT IN ('utente')", self.id, true).order(:ordine).first

      if index_property
        if index_property.tipo=='intero'
          ordinamento = "data.valore + 0 #{ sort_dir }"
        elsif index_property.tipo=='select'
          ordinamento = "i2.proxy #{ sort_dir }"
        end
      end
    end

    # if index_property && self.slug !~ /^[Ii]scrizione/
    # if false # ATTENZIONE: crea un problema se la index_property è di tipo utente
    if index_property
      # restituisce una collezione di istanze ordinate in base alla index property
      # @todo: se il dato non esiste quelle righe spariscono... può capitare nel campo di property aggiunte dopo che delle instances sono già state create
      # @todo: provato senza successo il left join

      # ordinamento di default:
      ordinamento = "data.valore #{ sort_dir }" if !ordinamento

      # Instance.joins(:data).where("instances.entity_id = ? AND data.property_id = ?", self.id, index_property.id).order(ordinamento)

      if index_property.tipo=='select'
        Instance.joins(:data).joins('left join instances as i2 on i2.id = data.valore').where("instances.entity_id = ? AND data.property_id = ?", self.id, index_property.id).order(ordinamento)
      else
        Instance.joins(:data).where("instances.entity_id = ? AND data.property_id = ?", self.id, index_property.id).order(ordinamento)
      end
    else
      if sort_by=='appartenenza'
        ordinamento = "i2.proxy #{ sort_dir }"
        Instance.joins("left join instances as i2 on i2.id = instances.appartenenza_id").where("instances.entity_id = ?", self.id).order(ordinamento)
      elsif sort_by=='utente'
        ordinamento = "users.email #{ sort_dir }"
        Instance.joins("left join users on users.id = instances.user_id").where("instances.entity_id = ?", self.id).order(ordinamento)
      else
        ordinamento = "id asc" if !ordinamento
        Instance.where("instances.entity_id = ?", self.id).order(ordinamento)
      end
    end
  end

  #def cerca_per_appartenenza
    # Instance.joins(:data).where("instances.entity_id = ? AND data.property_id = ?", self.id, index_property.id).order('data.valore ASC')
    # Instance.joins(:user).joins().where("instances.entity_id = ? AND data.property_id = ?", self.id, index_property.id).order('data.valore ASC')
    # nota: non potrebbe funzionare
  #end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_entity, only: [:show, :edit, :update, :destroy]

  # GET /entities
  # GET /entities.json
  def index
    authorize Entity

    @entities = Entity.all
  end

  def vetrina
    if current_user && current_user.admin?
      @entities = Entity.where("vetrina = ? AND stato < 3", true).order(:ordine, id: :desc)
    else
      @entities = Entity.where("vetrina = ? AND stato IN (1,2)", true).order(:ordine, id: :desc)
    end
  end

  # GET /entities/1
  # GET /entities/1.json
  def show
  end

  # GET /entities/new
  def new
    authorize Entity

    @entity = Entity.new
  end

  # GET /entities/1/edit
  def edit
  end

  # POST /entities
  # POST /entities.json
  def create
    @entity = Entity.new(entity_params)
    @entity.user = current_user

    authorize @entity

    respond_to do |format|
      if @entity.save
        format.html { redirect_to @entity, notice: 'Entity was successfully created.' }
        format.json { render :show, status: :created, location: @entity }
      else
        format.html { render :new }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entities/1
  # PATCH/PUT /entities/1.json
  def update
    if(params[:rigenera_slug])
      @entity.slug = nil
    end

    respond_to do |format|
      if @entity.update(entity_params)
        format.html { redirect_to vetrina_path, notice: 'Entity was successfully updated.' }
        format.json { render :show, status: :ok, location: @entity }
      else
        format.html { render :edit }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entities/1
  # DELETE /entities/1.json
  def destroy
    @entity.destroy
    respond_to do |format|
      format.html { redirect_to entities_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entity
      @entity = Entity.find(params[:id])

      authorize @entity
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entity_params
      params.require(:entity).permit(:titolo, :nativo, :rigenera_slug, :landing_page, :vetrina, :stato, :descrizione, :descrizione_lunga, :date, :plurale, :immagine, :icona_on, :icona_off, :tipo, :testo_pagamento, :ordine)
    end
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/views/entities/_form.html.erb
<%= form_for(@entity) do |f| %>
  <% if @entity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entity.errors.count, "error") %> prohibited this entity from being saved:</h2>

      <ul>
      <% @entity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titolo %><br>
    <%= f.text_field :titolo %>
  </div>
  <div class="field">
    <%= f.label :plurale %><br>
    <%= f.text_field :plurale %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.select(:tipo, options_for_select([['iscrizione','iscrizione'],['ordine','ordine'],['oggetto','oggetto']],@entity.tipo)) %>
  </div>
  <div class="field">
    <%= image_tag @entity.immagine.url(:thumb) if @entity.immagine.exists? %><br>
    <%= f.label :immagine %><br>
    <%= f.file_field :immagine %>
  </div>
  <div class="field">
    <%= image_tag @entity.icona_on.url(:thumb) %><br>
    <%= f.label "Icona per oggetti abilitati" %><br>
    <%= f.file_field :icona_on %>
  </div>
  <div class="field">
    <%= image_tag @entity.icona_off.url(:thumb) %><br>
    <%= f.label "Icona per oggetti disabilitati" %><br>
    <%= f.file_field :icona_off %>
  </div>
  <div class="field">
    <%= f.label "Date apertura iscrizioni" %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :descrizione %><br>
    <%= f.text_area :descrizione, rows: 3 %>
  </div>
  <div class="field">
    <%= f.label "Descrizione lunga" %><br>
    <%= f.text_area :descrizione_lunga, rows: 20 %>
  </div>
  <div class="field">
    <%= f.label "Modalità di pagamento" %><br>
    <%= f.text_area :testo_pagamento, rows: 10 %>
  </div>
  <div class="field">
    <%= f.label :landing_page, "Landing page" %><br>
    <%= f.text_field :landing_page %>
  </div>
  <div class="field">
    <%= f.check_box :vetrina %>
    <%= f.label "Deve apparire in vetrina" %>
  </div>
  <div class="field">
    <%= f.label "Ordine di apparizione in vetrina" %><br>
    <%= f.number_field :ordine %>
  </div>
  <div class="field">
    <%= f.label "Stato (0 = in costruzione / 1 = aperta / 2 = chiusa ma visibile)" %><br>
    <%= f.select(:stato, options_for_select([['in costruzione','0'],['aperta','1'],['chiusa ma visibile','2']],@entity.stato)) %>
  </div>
  <div class="field">
    <%= check_box_tag 'rigenera_slug' %>
    <%= f.label 'rigenera slug' %>
  </div>
  <div class="actions">
    <%= f.submit "SALVA", class: 'button' %>
  </div>
<% end %>

app/views/entities/edit.html.erb
<h1>Editing Entity</h1>

<%= render 'form' %>

app/views/entities/index.html.erb
<h1>Entities</h1>

<table>
  <thead>
    <tr>
      <th>Titolo</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @entities.each do |entity| %>
      <tr>
        <td><%= entity.titolo %></td>
        <td><%= link_to 'Edit', edit_entity_path(entity) %></td>
        <td><%= link_to 'Destroy', entity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entity', new_entity_path %>

app/views/entities/new.html.erb
<h1>New Entity</h1>

<%= render 'form' %>

<%= link_to 'Back', entities_path %>

app/views/entities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titolo:</strong>
  <%= @entity.titolo %>
</p>

<p>
  <strong>Nativo:</strong>
  <%= @entity.nativo %>
</p>

<%= link_to 'Edit', edit_entity_path(@entity) %> |
<%= link_to 'Back', entities_path %>

app/views/entities/vetrina.html.erb
<%= render partial: "pages/cookielaw" %>
<%= render partial: "pages/header" %>


<% if !current_user %>
<div class="column row text-center">
  <h1><img src="/img/lucchetto.png" style="width: 4rem;"><br>Login necessario</h1>
  <h2>Per iscriverti devi prima effettuare l'accesso al sito</h2>
</div>
<div class="row collapse">
  <div class="small-12 medium-6 columns">
    <a href="/users/sign_in"><img src="/img/sign_in.png"></a>
  </div>
  <div class="small-12 medium-6 columns">
    <a href="/users/sign_up"><img src="/img/sign_up.png"></a>
  </div>
</div>
<% end %>
<div class="column row" style="height: 1rem;"></div>

<div class="row small-up-1 medium-up-3">

  <% @entities.each do |entity| %>
      <div class="column column-block">
        <div class="card-user-profile">
        <% if entity.immagine.exists? %>
            <img class="card-user-profile-img" src="<%= entity.immagine.url(:medium) %>" />
        <% end %>
            <div class="card-user-profile-content card-section">
            <div class="card-user-profile-avatar">
              <img src="<%=
                if entity.stato != 1
                  entity.icona_off.url(:thumb)
                else
                  entity.icona_on.url(:thumb)
                end
              %>"></div>
            <p class="card-user-profile-name"><%= entity.titolo %></p>
            <p class="card-user-profile-date"><%= entity.date %></p>
            <p class="card-user-profile-info"><%= entity.descrizione %></p>
          </div>

          <div class="card-user-profile-actions">
            <%
              case entity.tipo
                when 'iscrizione'
                  bottone_new = 'Iscrivi'
                when 'ordine'
                  bottone_new = 'Ordina'
                when 'oggetto'
                  bottone_new = 'Nuovo'
                else
                  bottone_new = 'Nuovo'
              end

              if !current_user %>
              <a href="#" class="card-user-profile-button primary disabled button" title="Accedi per iscriverti."><%= bottone_new %></a>
              <a href="#" class="card-user-profile-button disabled secondary button" title="Accedi per iscriverti.">Elenco</a>
            <% elsif entity.stato == 1 || current_user.admin? %>
              <a href="/instances/new?type=<%= entity.slug %>" class="card-user-profile-button primary button"><%= bottone_new %></a>
              <a href="/instances?type=<%= entity.slug %>" class="card-user-profile-button secondary button">Elenco</a>
            <% else %>
              <a href="#" class="card-user-profile-button primary disabled button"><%= bottone_new %></a>
              <a href="/instances?type=<%= entity.slug %>" class="card-user-profile-button secondary button">Elenco</a>
            <% end %>
            <% if current_user && current_user.admin? %>
              <a href="<%= edit_entity_url(entity) %>" class="card-user-profile-button warning button">Modifica</a>
            <% end %>
          </div>
        </div>
      </div>
  <% end %>

  </div>

<%= render partial: "pages/footer" %>