config/routes.rb
Rails.application.routes.draw do

  get 'vetrina' => 'entities#vetrina'

  resources :grades
  resources :homeworks
  resources :assignments
  resources :instances
  resources :properties
  resources :entities
  resources :photos
  resources :photoalbums do
    member do
      get 'copertina'
      get 'pubblica'
    end
  end
  resources :tags

  resources :attachments do
    member do
      get 'download/:filename' => 'attachments#download'
      get 'pubblica'
    end
  end

  devise_for :users
  scope "/admin" do
    resources :users
  end

  mount Ckeditor::Engine => '/ckeditor'

  get 'login', to: redirect('/users/sign_in')
  get 'logout', to: redirect('/users/sign_out')

  resources :columns do
    member do
      post 'editor_update'
      post 'estendi_riga'
      post 'riduci_riga'
      post 'inserisci_riga_prima'
      post 'inserisci_riga_dopo'
      post 'elimina_riga'
      post 'inserisci_colonna_prima'
      post 'inserisci_colonna_dopo'
      post 'allarga_colonna'
      post 'stringi_colonna'
      post 'elimina_colonna'
      post 'rendi_statica'
      post 'elimina_contenuto_dinamico'
      post 'aggiungi_ruolo_titolo'
      post 'aggiungi_ruolo_abstract'
      post 'aggiungi_ruolo_testo'
      post 'cancella_ruolo'
      post 'contenuti_dinamici_pagina'
      post 'contenuti_dinamici_sezione'
      post 'contenuti_dinamici_sito'
      post 'sposta_riga_prima'
      post 'sposta_riga_dopo'
      post 'duplica_riga'
      post 'sposta_colonna_prima'
      post 'sposta_colonna_dopo'
      post 'equalizza_colonne'
      post 'autocrop_on'
      post 'autocrop_off'
      post 'mostra_sempre'
      post 'mostra_small_only'
      post 'mostra_big_only'
      post 'padding_00'
      post 'padding_01'
      post 'padding_02'
      post 'padding_03'
      post 'padding_04'
      post 'padding_05'
      post 'padding_10'
      post 'padding_15'
      post 'padding_20'
      post 'padding_25'
      post 'padding_30'
      get 'dialog_sfondo'
      get 'dialog_immagine'
      get 'modifica_immagine'
    end
  end

  resources :rows

  resources :sections

  resources :pages do
    member do
      get 'route'
      get 'row0'
      get 'pubblica'
      get 'duplica'
      get 'nascondi'
      post 'nuovo_contenuto_dinamico'
    end
  end

  resources :column_images do
    member do
      post 'elimina'
      post 'sposta_sx'
      post 'sposta_dx'
    end
  end

  get 'profile-updated' => 'users#profile_updated'
  get 'edit-profile' => 'users#edit_profile'
  get 'screen/:n' => 'pages#screen'
  get 'search' => 'pages#search'
  get 'tag-cloud-3d' => 'tags#cloud3d'
  get 'tag-cloud' => 'tags#cloud'
  get ':slug' => 'pages#route'
  get 'articoli/articolo.php' => 'pages#search'

  root 'pages#route', as: 'home'

end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :entity
  has_many :data, dependent: :destroy
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    authorize Property

    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    authorize Property

    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    authorize Property

    @property = Property.new(property_params)
    @property.maiuscolo = false if !['stringa', 'testo'].include? @property.tipo

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    params = property_params
    params[:maiuscolo] = false if !['stringa', 'testo'].include? params[:tipo]

    respond_to do |format|
      if @property.update(params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])

      authorize @property
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:nome, :tipo, :nativo, :entity_id, :maiuscolo, :obbligatorio, :riservata, :condizioni, :ordine, :descrizione, :placeholder, :default, :indice)
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= form_for(@property) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :entity_id %><br>
    <%= f.collection_select(:entity_id, Entity.all, :id, :titolo) %>
  </div>
  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.text_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :condizioni %><br>
    <%= f.text_area :condizioni %>
  </div>
  <div class="field">
    <%= f.label :placeholder %><br>
    <%= f.text_field :placeholder %>
  </div>
  <div class="field">
    <%= f.label :descrizione %><br>
    <%= f.text_area :descrizione %>
  </div>
  <div class="field">
    <%= f.label :ordine %><br>
    <%= f.number_field :ordine %>
  </div>
  <div class="field">
    <%= f.label :nativo %><br>
    <%= f.check_box :nativo %>
  </div>
  <div class="field">
    <%= f.label :maiuscolo %><br>
    <%= f.check_box :maiuscolo %>
  </div>
  <div class="field">
    <%= f.label :obbligatorio %><br>
    <%= f.check_box :obbligatorio %>
  </div>
  <div class="field">
    <%= f.label :riservata %><br>
    <%= f.check_box :riservata %>
  </div>
  <div class="field">
    <%= f.label :indice %><br>
    <%= f.check_box :indice %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form' %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Properties</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Tipo</th>
      <th>Nativo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.nome %></td>
        <td><%= property.tipo %></td>
        <td><%= property.nativo %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path %>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form' %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @property.nome %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @property.tipo %>
</p>

<p>
  <strong>Nativo:</strong>
  <%= @property.nativo %>
</p>

<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>