config/routes.rb
Rails.application.routes.draw do

  get 'vetrina' => 'entities#vetrina'

  resources :grades
  resources :homeworks
  resources :assignments
  resources :instances
  resources :properties
  resources :entities
  resources :photos
  resources :photoalbums do
    member do
      get 'copertina'
      get 'pubblica'
    end
  end
  resources :tags

  resources :attachments do
    member do
      get 'download/:filename' => 'attachments#download'
      get 'pubblica'
    end
  end

  devise_for :users
  scope "/admin" do
    resources :users
  end

  mount Ckeditor::Engine => '/ckeditor'

  get 'login', to: redirect('/users/sign_in')
  get 'logout', to: redirect('/users/sign_out')

  resources :columns do
    member do
      post 'editor_update'
      post 'estendi_riga'
      post 'riduci_riga'
      post 'inserisci_riga_prima'
      post 'inserisci_riga_dopo'
      post 'elimina_riga'
      post 'inserisci_colonna_prima'
      post 'inserisci_colonna_dopo'
      post 'allarga_colonna'
      post 'stringi_colonna'
      post 'elimina_colonna'
      post 'rendi_statica'
      post 'elimina_contenuto_dinamico'
      post 'aggiungi_ruolo_titolo'
      post 'aggiungi_ruolo_abstract'
      post 'aggiungi_ruolo_testo'
      post 'cancella_ruolo'
      post 'contenuti_dinamici_pagina'
      post 'contenuti_dinamici_sezione'
      post 'contenuti_dinamici_sito'
      post 'sposta_riga_prima'
      post 'sposta_riga_dopo'
      post 'duplica_riga'
      post 'sposta_colonna_prima'
      post 'sposta_colonna_dopo'
      post 'equalizza_colonne'
      post 'autocrop_on'
      post 'autocrop_off'
      post 'mostra_sempre'
      post 'mostra_small_only'
      post 'mostra_big_only'
      post 'padding_00'
      post 'padding_01'
      post 'padding_02'
      post 'padding_03'
      post 'padding_04'
      post 'padding_05'
      post 'padding_10'
      post 'padding_15'
      post 'padding_20'
      post 'padding_25'
      post 'padding_30'
      get 'dialog_sfondo'
      get 'dialog_immagine'
      get 'modifica_immagine'
    end
  end

  resources :rows

  resources :sections

  resources :pages do
    member do
      get 'route'
      get 'row0'
      get 'pubblica'
      get 'duplica'
      get 'nascondi'
      post 'nuovo_contenuto_dinamico'
    end
  end

  resources :column_images do
    member do
      post 'elimina'
      post 'sposta_sx'
      post 'sposta_dx'
    end
  end

  get 'profile-updated' => 'users#profile_updated'
  get 'edit-profile' => 'users#edit_profile'
  get 'screen/:n' => 'pages#screen'
  get 'search' => 'pages#search'
  get 'tag-cloud-3d' => 'tags#cloud3d'
  get 'tag-cloud' => 'tags#cloud'
  get ':slug' => 'pages#route'
  get 'articoli/articolo.php' => 'pages#search'

  root 'pages#route', as: 'home'

end

app/models/section.rb
# sezione del sito

class Section < ActiveRecord::Base
  validates :titolo, :descrizione, presence: true

  has_many :pages, dependent: :destroy
  has_many :attachments, dependent: :destroy
  has_many :users, dependent: :nullify
  has_many :photoalbums, dependent: :destroy

  def trova_modello
    # cerchiamo un modello
    # esiste un modello per questa sezione?
    modello = Page.find_by section: self, modello: true

    # se non esiste cerco un modello nella sezione principale
    if !modello
      sezione = trova_principale
      modello = Page.find_by section: sezione, modello: true
    end

    modello
  end

  def trova_principale
    Section.find_by principale: true
  end

  def trova_home
    Page.find_by section: self, home: true
  end
end

app/controllers/sections_controller.rb
# Sections: sezioni del sito; ogni sezione ha le sue pagine, articoli, fotografie, allegati
#           e può essere gestita da uno o più utenti

class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
    authorize @sections
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
    authorize Section
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)
    authorize Section

    respond_to do |format|
      if @section.save

        # solo una sezione può avere il flag principale
        if(@section.principale)
          Section.where.not(id: @section.id).update_all(principale: false)
        end

        format.html { redirect_to sections_url }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)

        # solo una sezione può avere il flag principale
        if(@section.principale)
          Section.where.not(id: @section.id).update_all(principale: false)
        end

        format.html { redirect_to sections_url }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
      authorize @section
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:titolo, :percorso, :descrizione, :principale)
    end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%= form_for(@section) do |f| %>
  <% if @section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% @section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titolo %><br>
    <%= f.text_field :titolo %>
  </div>
  <div class="field">
    <%= f.label :percorso %><br>
    <%= f.text_field :percorso %>
  </div>
  <div class="field">
    <%= f.label :descrizione %><br>
    <%= f.text_area :descrizione %>
  </div>
  <div class="field">
    <%= f.check_box :principale %>
    <%= f.label :principale %>
  </div>

  <div class="actions">
    <%= f.submit 'SALVA', class:'button' %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<%= render 'form' %>

app/views/sections/index.html.erb
<h1>Sezioni del sito
  <%= link_to 'NUOVA SEZIONE', new_section_path, class: 'large warning button float-right' %>
</h1>


<% @sections.each do |section| %>
    <div class="expanded row">
      <div class="large-3 columns"><%= link_to '<i class="fi-paperclip"></i> '.html_safe + " " + "/#{section.percorso}", "/#{section.percorso}", class: "medium secondary button bottone-largo" %></div>
      <div class="large-4 columns">
        <%= "<span class='warning label'>principale</span>".html_safe if section.principale %>
        <b><%= section.titolo %></b>
        <br><%= section.descrizione %>
      </div>
      <div class="large-5 columns">
        <%= link_to 'Nuova pagina', new_page_path(:section_id => section.id), class: "tiny warning button" %>
        <%= link_to 'Nuovo articolo', new_page_path(:section_id => section.id, :articolo => 1), class: "tiny warning button" %>
        <%= link_to 'Nuovo album', new_photoalbum_path(:section_id => section.id), class: "tiny warning button" %>
        <%= link_to 'Nuovo allegato', new_attachment_path(:section_id => section.id), class: "tiny warning button" %>
        <%= link_to 'Proprietà', edit_section_path(section), class: "tiny primary button" %>
        <%= link_to 'Elimina', section, method: :delete, data: { confirm: 'Sei sicuro? Verranno cancellate tutte le pagine di questa sezione...' }, class: "tiny alert button" %>
      </div>
    </div>
<% end %>

app/views/sections/new.html.erb
<h1>Nuova sezione</h1>

<%= render 'form' %>